### PR TITLE
port to julia 0.6

### PR DESCRIPTION
**Pull request by bjarthur**
sadly, the tests seg fault when `optimize` is called.  not sure what's going on.  @HarlanH could you take a look into it?  thanks.

### CODE REVIEW

**Comment by HarlanH** [comment]
Hi bj -- I have no idea, and haven't had time to work on Julia at all for quite some time. I don't think I even have a working install set up anywhere. I'm happy to merge your PR, though, if you'd like. Let me know!

**Comment by bjarthur** [comment]
i fixed the NLOpt segfaults by changing `alg = :GN_CRS2_LM` to `alg = :GN_ORIG_DIRECT_L`.  i tried several others and that was the first that worked.  didn't take the time to understand why.

tests now pass on 0.6.  will start working on porting to 0.7....

**Comment by bjarthur** [comment]
actually, all but one test using `GN_ORIG_DIRECT_L`, though it didn't seg fault, did return `MAXTIME_REACHED`.  switched to `GN_ORIG_DIRECT` and now they all succeed.

**Comment by bjarthur** [comment]
are you fine with the change to the algorithm?

Femtocleaner apparently only upgrades the master branch to 0.7, so this needs to merge before i can make any further progress...

**Comment by bjarthur** [comment]
there will be a lot more for 0.7.  but many are automated with FemotCleaner, and then we're done, because no new changes were introduced with 1.0, just the removal of deprecations.

**Pull request merged**
